### ISSUE TITLE
Support for Graylog 2.4

### ISSUE THREAD

**Issue by stijnvanrenterghem** [sherzberg/graylog-plugin-s3#14]
Hi,

In the README I see that Graylog version < 2.3.0 is supported.
Does the plugin support Graylog version 2.4 or will it be supported?

Thanks.

**Comment by sherzberg** [comment]
@stijnvanrenterghem sorry for the delay, we are actually using the current version of this plugin in graylog 2.4.6. I will get the readme updated!

**Comment by sherzberg** [comment]
I updated the readme in #17. Let me know if you need more info!

**Comment by stijnvanrenterghem** [comment]
Thanks
