### ISSUE TITLE
Url-decode the s3 object

### ISSUE THREAD

**Issue by pjvaanan** [sherzberg/graylog-plugin-s3#2]
Fetching a s3 file fails if the file name has a colon in it (e.g. Redshift access log).

S3SNSNotificationParser should call record.getS3().getObject().getUrlDecodedKey() instead of record.getS3().getObject().getKey()

**Comment by sherzberg** [comment]
Thanks for adding this issue! Please try out the latest release: https://github.com/sherzberg/graylog-plugin-s3/releases/tag/2.3.0-1 and let us know how it works out!
